name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liqOGTwcpbI6NN5W"
GITHUB_OWNER = "turkey2077"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://mk48.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://mk48.pages.dev"

